In [2]:
import json
import pandas as pd

# Part 1: Reading and investigating data

Open up the `player_data.json` and investigate the data structure.

In [19]:
#your code here
with open('player_data.json') as file:
    data = json.load(file)

In [20]:
data[0]

{'PERSON_ID': 203518,
 'FIRST_NAME': 'Alex',
 'LAST_NAME': 'Abrines',
 'DISPLAY_FIRST_LAST': 'Alex Abrines',
 'DISPLAY_LAST_COMMA_FIRST': 'Abrines, Alex',
 'DISPLAY_FI_LAST': 'A. Abrines',
 'BIRTHDATE': '1993-08-01T00:00:00',
 'SCHOOL': ' ',
 'COUNTRY': 'Spain',
 'LAST_AFFILIATION': 'Spain/Spain',
 'HEIGHT': '',
 'WEIGHT': '',
 'SEASON_EXP': 2,
 'JERSEY': '',
 'POSITION': '',
 'ROSTERSTATUS': 'Inactive',
 'TEAM_ID': 0,
 'TEAM_NAME': '',
 'TEAM_ABBREVIATION': '',
 'TEAM_CODE': '',
 'TEAM_CITY': '',
 'PLAYERCODE': 'alex_abrines',
 'FROM_YEAR': 2016,
 'TO_YEAR': 2018,
 'DLEAGUE_FLAG': 'N',
 'NBA_FLAG': 'Y',
 'GAMES_PLAYED_FLAG': 'Y',
 'DRAFT_YEAR': '2013',
 'DRAFT_ROUND': '2',
 'DRAFT_NUMBER': '32',
 'CAREER_STATS': {'PTS': 5.3,
  'AST': 0.5,
  'REB': 1.4,
  'ALL_STAR_APPEARANCES': 0},
 'GAMELOG': [{'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800772',
   'GAME_DATE': 'FEB 01, 2019',
   'MATCHUP': 'OKC @ MIA',
   'WL': 'W',
   'MIN': 9,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 0,
   'PLUS_MINUS': -8,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800751',
   'GAME_DATE': 'JAN 29, 2019',
   'MATCHUP': 'OKC @ ORL',
   'WL': 'W',
   'MIN': 6,
   'FGM': 1,
   'FGA': 2,
   'FG_PCT': 0.5,
   'FG3M': 1,
   'FG3A': 2,
   'FG3_PCT': 0.5,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 3,
   'PLUS_MINUS': 4,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800493',
   'GAME_DATE': 'DEC 23, 2018',
   'MATCHUP': 'OKC vs. MIN',
   'WL': 'L',
   'MIN': 27,
   'FGM': 2,
   'FGA': 6,
   'FG_PCT': 0.333,
   'FG3M': 1,
   'FG3A': 5,
   'FG3_PCT': 0.2,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 0,
   'STL': 0,
   'BLK': 2,
   'TOV': 0,
   'PF': 2,
   'PTS': 7,
   'PLUS_MINUS': 1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800485',
   'GAME_DATE': 'DEC 22, 2018',
   'MATCHUP': 'OKC @ UTA',
   'WL': 'W',
   'MIN': 16,
   'FGM': 2,
   'FGA': 4,
   'FG_PCT': 0.5,
   'FG3M': 2,
   'FG3A': 4,
   'FG3_PCT': 0.5,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 4,
   'PTS': 6,
   'PLUS_MINUS': 13,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800466',
   'GAME_DATE': 'DEC 19, 2018',
   'MATCHUP': 'OKC @ SAC',
   'WL': 'W',
   'MIN': 23,
   'FGM': 3,
   'FGA': 7,
   'FG_PCT': 0.429,
   'FG3M': 3,
   'FG3A': 7,
   'FG3_PCT': 0.429,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 4,
   'PTS': 9,
   'PLUS_MINUS': 6,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800447',
   'GAME_DATE': 'DEC 17, 2018',
   'MATCHUP': 'OKC vs. CHI',
   'WL': 'W',
   'MIN': 14,
   'FGM': 3,
   'FGA': 4,
   'FG_PCT': 0.75,
   'FG3M': 2,
   'FG3A': 3,
   'FG3_PCT': 0.667,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 2,
   'DREB': 1,
   'REB': 3,
   'AST': 0,
   'STL': 1,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 8,
   'PLUS_MINUS': 4,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800434',
   'GAME_DATE': 'DEC 15, 2018',
   'MATCHUP': 'OKC vs. LAC',
   'WL': 'W',
   'MIN': 20,
   'FGM': 2,
   'FGA': 4,
   'FG_PCT': 0.5,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 4,
   'REB': 4,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 0,
   'PTS': 6,
   'PLUS_MINUS': 7,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800426',
   'GAME_DATE': 'DEC 14, 2018',
   'MATCHUP': 'OKC @ DEN',
   'WL': 'L',
   'MIN': 19,
   'FGM': 0,
   'FGA': 1,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 0,
   'PTS': 0,
   'PLUS_MINUS': -1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800411',
   'GAME_DATE': 'DEC 12, 2018',
   'MATCHUP': 'OKC @ NOP',
   'WL': 'L',
   'MIN': 14,
   'FGM': 2,
   'FGA': 6,
   'FG_PCT': 0.333,
   'FG3M': 1,
   'FG3A': 5,
   'FG3_PCT': 0.2,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 2,
   'STL': 1,
   'BLK': 0,
   'TOV': 0,
   'PF': 0,
   'PTS': 5,
   'PLUS_MINUS': 0,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800396',
   'GAME_DATE': 'DEC 10, 2018',
   'MATCHUP': 'OKC vs. UTA',
   'WL': 'W',
   'MIN': 19,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 3,
   'REB': 3,
   'AST': 0,
   'STL': 1,
   'BLK': 0,
   'TOV': 2,
   'PF': 1,
   'PTS': 0,
   'PLUS_MINUS': -12,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800373',
   'GAME_DATE': 'DEC 07, 2018',
   'MATCHUP': 'OKC @ CHI',
   'WL': 'L',
   'MIN': 15,
   'FGM': 1,
   'FGA': 4,
   'FG_PCT': 0.25,
   'FG3M': 1,
   'FG3A': 4,
   'FG3_PCT': 0.25,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 3,
   'REB': 3,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 3,
   'PTS': 3,
   'PLUS_MINUS': -15,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800358',
   'GAME_DATE': 'DEC 05, 2018',
   'MATCHUP': 'OKC @ BKN',
   'WL': 'W',
   'MIN': 19,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 3,
   'BLK': 0,
   'TOV': 1,
   'PF': 1,
   'PTS': 0,
   'PLUS_MINUS': -10,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800343',
   'GAME_DATE': 'DEC 03, 2018',
   'MATCHUP': 'OKC @ DET',
   'WL': 'W',
   'MIN': 18,
   'FGM': 1,
   'FGA': 3,
   'FG_PCT': 0.333,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 1,
   'PTS': 2,
   'PLUS_MINUS': -1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800325',
   'GAME_DATE': 'NOV 30, 2018',
   'MATCHUP': 'OKC vs. ATL',
   'WL': 'W',
   'MIN': 26,
   'FGM': 7,
   'FGA': 11,
   'FG_PCT': 0.636,
   'FG3M': 7,
   'FG3A': 11,
   'FG3_PCT': 0.636,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 2,
   'PTS': 21,
   'PLUS_MINUS': 6,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800313',
   'GAME_DATE': 'NOV 28, 2018',
   'MATCHUP': 'OKC vs. CLE',
   'WL': 'W',
   'MIN': 27,
   'FGM': 1,
   'FGA': 9,
   'FG_PCT': 0.111,
   'FG3M': 1,
   'FG3A': 8,
   'FG3_PCT': 0.125,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 1,
   'DREB': 2,
   'REB': 3,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 3,
   'PLUS_MINUS': 13,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800282',
   'GAME_DATE': 'NOV 24, 2018',
   'MATCHUP': 'OKC vs. DEN',
   'WL': 'L',
   'MIN': 8,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 0,
   'PLUS_MINUS': -9,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800274',
   'GAME_DATE': 'NOV 23, 2018',
   'MATCHUP': 'OKC vs. CHA',
   'WL': 'W',
   'MIN': 7,
   'FGM': 0,
   'FGA': 1,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 4,
   'PTS': 0,
   'PLUS_MINUS': 1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800209',
   'GAME_DATE': 'NOV 14, 2018',
   'MATCHUP': 'OKC vs. NYK',
   'WL': 'W',
   'MIN': 7,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 0,
   'PTS': 0,
   'PLUS_MINUS': 3,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800196',
   'GAME_DATE': 'NOV 12, 2018',
   'MATCHUP': 'OKC vs. PHX',
   'WL': 'W',
   'MIN': 20,
   'FGM': 2,
   'FGA': 6,
   'FG_PCT': 0.333,
   'FG3M': 2,
   'FG3A': 6,
   'FG3_PCT': 0.333,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 2,
   'STL': 2,
   'BLK': 1,
   'TOV': 1,
   'PF': 4,
   'PTS': 8,
   'PLUS_MINUS': -11,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800181',
   'GAME_DATE': 'NOV 10, 2018',
   'MATCHUP': 'OKC @ DAL',
   'WL': 'L',
   'MIN': 26,
   'FGM': 2,
   'FGA': 6,
   'FG_PCT': 0.333,
   'FG3M': 2,
   'FG3A': 4,
   'FG3_PCT': 0.5,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 2,
   'PTS': 6,
   'PLUS_MINUS': -9,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800163',
   'GAME_DATE': 'NOV 08, 2018',
   'MATCHUP': 'OKC vs. HOU',
   'WL': 'W',
   'MIN': 19,
   'FGM': 0,
   'FGA': 3,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 3,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 1,
   'DREB': 3,
   'REB': 4,
   'AST': 0,
   'STL': 1,
   'BLK': 0,
   'TOV': 1,
   'PF': 0,
   'PTS': 0,
   'PLUS_MINUS': -8,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800153',
   'GAME_DATE': 'NOV 07, 2018',
   'MATCHUP': 'OKC @ CLE',
   'WL': 'W',
   'MIN': 26,
   'FGM': 3,
   'FGA': 12,
   'FG_PCT': 0.25,
   'FG3M': 3,
   'FG3A': 10,
   'FG3_PCT': 0.3,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 1,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 9,
   'PLUS_MINUS': 11,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800144',
   'GAME_DATE': 'NOV 05, 2018',
   'MATCHUP': 'OKC vs. NOP',
   'WL': 'W',
   'MIN': 30,
   'FGM': 2,
   'FGA': 4,
   'FG_PCT': 0.5,
   'FG3M': 1,
   'FG3A': 2,
   'FG3_PCT': 0.5,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 4,
   'REB': 4,
   'AST': 3,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 1,
   'PTS': 7,
   'PLUS_MINUS': 6,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800119',
   'GAME_DATE': 'NOV 02, 2018',
   'MATCHUP': 'OKC @ WAS',
   'WL': 'W',
   'MIN': 24,
   'FGM': 3,
   'FGA': 8,
   'FG_PCT': 0.375,
   'FG3M': 2,
   'FG3A': 7,
   'FG3_PCT': 0.286,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 2,
   'STL': 0,
   'BLK': 2,
   'TOV': 0,
   'PF': 3,
   'PTS': 8,
   'PLUS_MINUS': 27,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800111',
   'GAME_DATE': 'NOV 01, 2018',
   'MATCHUP': 'OKC @ CHA',
   'WL': 'W',
   'MIN': 30,
   'FGM': 9,
   'FGA': 15,
   'FG_PCT': 0.6,
   'FG3M': 5,
   'FG3A': 10,
   'FG3_PCT': 0.5,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 4,
   'PTS': 25,
   'PLUS_MINUS': 16,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800103',
   'GAME_DATE': 'OCT 30, 2018',
   'MATCHUP': 'OKC vs. LAC',
   'WL': 'W',
   'MIN': 15,
   'FGM': 1,
   'FGA': 2,
   'FG_PCT': 0.5,
   'FG3M': 1,
   'FG3A': 1,
   'FG3_PCT': 1.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 4,
   'BLK': 1,
   'TOV': 1,
   'PF': 5,
   'PTS': 3,
   'PLUS_MINUS': -1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800085',
   'GAME_DATE': 'OCT 28, 2018',
   'MATCHUP': 'OKC vs. PHX',
   'WL': 'W',
   'MIN': 24,
   'FGM': 0,
   'FGA': 5,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 3,
   'FG3_PCT': 0.0,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 0,
   'STL': 2,
   'BLK': 0,
   'TOV': 0,
   'PF': 2,
   'PTS': 2,
   'PLUS_MINUS': -1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800065',
   'GAME_DATE': 'OCT 25, 2018',
   'MATCHUP': 'OKC vs. BOS',
   'WL': 'L',
   'MIN': 19,
   'FGM': 2,
   'FGA': 5,
   'FG_PCT': 0.4,
   'FG3M': 2,
   'FG3A': 5,
   'FG3_PCT': 0.4,
   'FTM': 0,
   'FTA': 1,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 2,
   'PTS': 6,
   'PLUS_MINUS': 6,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800037',
   'GAME_DATE': 'OCT 21, 2018',
   'MATCHUP': 'OKC vs. SAC',
   'WL': 'L',
   'MIN': 5,
   'FGM': 0,
   'FGA': 1,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 2,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 0,
   'PTS': 0,
   'PLUS_MINUS': 5,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800025',
   'GAME_DATE': 'OCT 19, 2018',
   'MATCHUP': 'OKC @ LAC',
   'WL': 'L',
   'MIN': 32,
   'FGM': 4,
   'FGA': 10,
   'FG_PCT': 0.4,
   'FG3M': 2,
   'FG3A': 7,
   'FG3_PCT': 0.286,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 1,
   'DREB': 1,
   'REB': 2,
   'AST': 1,
   'STL': 1,
   'BLK': 0,
   'TOV': 2,
   'PF': 0,
   'PTS': 10,
   'PLUS_MINUS': -9,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800002',
   'GAME_DATE': 'OCT 16, 2018',
   'MATCHUP': 'OKC @ GSW',
   'WL': 'L',
   'MIN': 23,
   'FGM': 3,
   'FGA': 8,
   'FG_PCT': 0.375,
   'FG3M': 2,
   'FG3A': 6,
   'FG3_PCT': 0.333,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 2,
   'PTS': 8,
   'PLUS_MINUS': -5,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760}]}

# Part 2:  Creating the Dataframe

Create a data frame where each row corresponds to a game for each player. You must have atleast the following columns in your final dataframe:

'DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID', 'AST', 'BLK', 'STL','Game_ID',  'MIN', 'PTS', 'REB', 'TEAM_ABBREVIATION'

*You can include additional columns in your dataframe, so you don't have to do additional work to remove other columns.*

In [21]:
df = pd.DataFrame()

for person in data:
    if len(person['GAMELOG']) == 0:
        continue
    df1 = pd.DataFrame(person, columns=['DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID'], index=[0])
    df2 = pd.DataFrame(person['GAMELOG'])
    merged = pd.merge(df1, df2, left_on='PERSON_ID', right_on='Player_ID', how='outer')
    df = pd.concat([df, merged])
    
df.reset_index(drop=True, inplace=True)

In [22]:
df.head()

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
0,Alex Abrines,203518,0,0,0,0,1,0,0.000,2,...,0,203518,0,22018,0,OKC,1610612760,0,1,W
1,Alex Abrines,203518,0,0,0,1,2,1,0.500,2,...,3,203518,1,22018,0,OKC,1610612760,0,1,W
2,Alex Abrines,203518,0,0,2,1,5,1,0.200,6,...,7,203518,1,22018,0,OKC,1610612760,0,1,L
3,Alex Abrines,203518,0,0,0,1,4,2,0.500,4,...,6,203518,1,22018,0,OKC,1610612760,0,1,W
4,Alex Abrines,203518,0,1,0,1,7,3,0.429,7,...,9,203518,1,22018,0,OKC,1610612760,0,1,W

# Part 3: Pandas Questions

Answer the following questions

## 1 
- Find the player who scored the most points in an individual game last season.

-  Now do the same for rebounds, blocks, and assists.

In [61]:
# Your code here
pts_max = df.groupby("DISPLAY_FIRST_LAST")["PTS"].max().max()
pts_max
df[df.PTS == pts_max]

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
10323,James Harden,201935,1610612745,1,0,5,13,9,0.692,34,...,61,201935,7,22018,3,HOU,1610612745,3,1,W
10348,James Harden,201935,1610612745,4,0,9,20,5,0.250,38,...,61,201935,15,22018,5,HOU,1610612745,5,1,W

## 2: 

- Find the player who scored the most points for the entire season.

- Now do the same for rebounds, blocks, and assists.

In [101]:
#your code here
pts_most = df.groupby("DISPLAY_FIRST_LAST")["PTS"].sum().max()
pts_most
df.groupby("DISPLAY_FIRST_LAST")["PTS"].sum()[(df.groupby("DISPLAY_FIRST_LAST")["PTS"].sum() == pts_most)]

DISPLAY_FIRST_LAST
James Harden    2818
Name: PTS, dtype: int64

## 3:
How many players played in at least 82 games last season?

In [103]:
#your code here
df.groupby("DISPLAY_FIRST_LAST")["PTS"].count() >= 82
df.groupby("DISPLAY_FIRST_LAST")["PTS"].count()[(df.groupby("DISPLAY_FIRST_LAST")["PTS"].count() >= 82)].count()

21

## 4: 
- Find which team scored the most points for the entire season.

- Now do the same for rebounds, blocks, and assists.

In [104]:
# your code here
# team_most_points = df.groupby("TEAM_ABBREVIATION")["PTS"].sum().max()
# team_most_points
df.groupby("TEAM_ABBREVIATION")["PTS"].sum().idxmax()

'MIL'

## 5:
Which team had the most players play for them last season?

In [113]:
#your code here
df.groupby("TEAM_ABBREVIATION").nunique()["DISPLAY_FIRST_LAST"].idxmax()

'MEM'

## 6:
- Did any player play for more than one team last year?

- What is the most number of teams a player played for last season?

In [116]:
df.groupby(["DISPLAY_FIRST_LAST", "PERSON_ID"]).nunique()

,,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
DISPLAY_FIRST_LAST,PERSON_ID,,,,,,,,,,,,,,,,,,,,,
Aaron Gordon,203932,1,1,1,10,4,12,11,5,16,16,...,26,1,16,1,4,1,1,7,2,2
Aaron Holiday,1628988,1,1,1,8,3,8,9,5,10,13,...,14,1,7,1,4,1,1,4,1,2
Abdel Nader,1627846,1,1,1,4,4,7,7,4,9,12,...,14,1,8,1,3,1,1,4,1,2
Al Horford,201143,1,1,1,11,6,11,10,6,13,15,...,22,1,15,1,5,1,1,6,2,2
Al-Farouq Aminu,202329,1,1,1,5,4,12,9,5,14,12,...,21,1,15,1,4,1,1,5,2,2
Alan Williams,1626210,1,1,1,3,1,4,2,1,1,4,...,4,1,5,1,2,1,1,2,1,2
Alec Burks,202692,1,1,1,8,4,10,8,5,12,18,...,21,1,11,1,4,3,3,5,1,2
Alex Abrines,203518,1,1,1,4,3,5,10,6,13,13,...,11,1,5,1,5,1,1,3,1,2
Alex Caruso,1627936,1,1,1,10,4,8,6,5,6,12,...,15,1,10,1,5,1,1,6,2,2
Alex Len,203458,1,1,1,5,5,10,10,7,14,21,...,26,1,14,1,3,1,1,5,2,2
Alex Poythress,1627816,1,1,1,5,3,6,4,3,5,8,...,10,1,9,1,2,1,1,4,1,2
Alfonzo McKinnie,1628035,1,1,1,4,3,8,8,5,9,12,...,13,1,11,1,3,1,1,3,1,2
Alize Johnson,1628993,1,1,1,2,3,5,2,2,2,4,...,5,1,4,1,2,1,1,1,1,2
Allen Crabbe,203459,1,1,1,5,2,9,11,8,19,12,...,17,1,10,1,3,1,1,4,1,2
Allonzo Trier,1629019,1,1,1,8,4,9,6,5,9,17,...,26,1,9,1,4,1,1,5,2,2
Amile Jefferson,1628518,1,1,1,2,2,4,1,1,1,5,...,5,1,5,1,2,1,1,2,1,2
Amir Johnson,101161,1,1,1,5,3,7,4,3,5,9,...,13,1,10,1,3,1,1,5,1,2
Andre Drummond,203083,1,1,1,6,7,15,4,2,4,20,...,27,1,20,1,6,1,1,7,2,2
Andre Iguodala,2738,1,1,1,8,4,8,8,4,10,12,...,17,1,9,1,4,1,1,4,1,2
Andre Ingram,201281,1,1,1,1,1,2,2,1,1,3,...,1,1,2,1,2,1,1,2,1,2
Andrew Bogut,101106,1,1,1,3,4,6,1,1,1,7,...,6,1,7,1,2,1,1,3,1,2
Andrew Harrison,1626150,1,1,1,6,2,4,5,2,5,8,...,8,1,5,1,3,3,3,3,1,2
Andrew Wiggins,203952,1,1,1,8,4,10,11,5,16,18,...,26,1,12,1,4,1,1,7,2,2
Anfernee Simons,1629014,1,1,1,4,1,3,5,3,4,8,...,8,1,4,1,2,1,1,3,1,2
Angel Delgado,1629116,1,1,1,1,1,2,1,1,1,2,...,2,1,2,1,2,1,1,1,1,1
Ante Zizic,1627790,1,1,1,5,3,11,1,1,1,14,...,20,1,14,1,3,1,1,6,1,2
Anthony Davis,203076,1,1,1,10,6,14,8,5,10,22,...,29,1,18,1,6,1,1,7,2,2
Anthony Tolliver,201229,1,1,1,5,4,9,9,6,14,10,...,16,1,9,1,3,1,1,4,2,2
Antonio Blakeney,1628469,1,1,1,5,3,7,7,5,9,18,...,19,1,7,1,3,1,1,4,2,2
Aron Baynes,203382,1,1,1,5,4,9,6,3,6,12,...,13,1,13,1,2,1,1,3,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tyler Zeller,203092,1,1,1,3,3,3,2,1,1,5,...,5,1,5,1,2,2,2,3,1,2
Tyreke Evans,201936,1,1,1,8,3,8,9,6,12,12,...,21,1,10,1,5,1,1,7,1,2
Tyrone Wallace,1627820,1,1,1,6,3,5,3,2,3,11,...,12,1,7,1,4,1,1,4,2,2
Tyson Chandler,2199,1,1,1,4,4,12,2,1,1,8,...,12,1,15,1,3,2,2,5,1,2
Tyus Jones,1626145,1,1,1,13,2,7,7,4,8,16,...,16,1,7,1,6,1,1,5,2,2
Udonis Haslem,2617,1,1,1,2,1,6,4,1,1,5,...,4,1,5,1,1,1,1,3,1,2
Victor Oladipo,203506,1,1,1,10,4,12,13,6,15,18,...,18,1,12,1,6,1,1,7,1,2
Vince Carter,1713,1,1,1,6,3,8,12,7,16,15,...,20,1,9,1,4,1,1,4,2,2
Vincent Edwards,1629053,1,1,1,1,1,2,1,2,2,1,...,2,1,1,1,1,1,1,1,1,2
Wade Baldwin IV,1627735,1,1,1,4,2,4,3,2,2,6,...,5,1,4,1,2,1,1,3,1,2
Walter Lemon Jr.,1627215,1,1,1,5,2,4,3,2,2,5,...,6,1,5,1,4,1,1,4,1,2
Wayne Ellington,201961,1,1,1,5,3,6,14,8,22,17,...,21,1,7,1,6,2,2,5,2,2
Wayne Selden,1627782,1,1,1,6,3,9,7,5,8,16,...,18,1,9,1,5,2,2,5,2,2
Wendell Carter Jr.,1628976,1,1,1,7,5,11,4,3,4,12,...,19,1,12,1,4,1,1,4,1,2
Wes Iwundu,1628411,1,1,1,5,3,8,5,3,5,11,...,13,1,9,1,4,1,1,4,2,2
Wesley Johnson,202325,1,1,1,4,2,7,6,4,8,8,...,10,1,8,1,3,2,2,4,1,2
Wesley Matthews,202083,1,1,1,6,3,6,12,8,22,16,...,24,1,8,1,4,3,3,5,1,2
Will Barton,203115,1,1,1,8,3,10,10,6,11,12,...,22,1,11,1,3,1,1,6,1,2
Willie Cauley-Stein,1626161,1,1,1,8,6,14,2,2,2,17,...,25,1,16,1,6,1,1,5,2,2
Willy Hernangomez,1626195,1,1,1,5,3,10,5,4,3,13,...,17,1,14,1,3,1,1,4,1,2
Wilson Chandler,201163,1,1,1,6,4,10,8,6,10,11,...,14,1,10,1,3,2,2,4,2,2
Yante Maten,1628999,1,1,1,1,1,2,2,1,1,1,...,2,1,2,1,2,1,1,1,1,2
Yogi Ferrell,1627812,1,1,1,7,2,6,7,5,8,12,...,16,1,6,1,4,1,1,3,2,2
Yuta Watanabe,1629139,1,1,1,3,2,5,4,2,2,6,...,6,1,6,1,2,1,1,2,1,2
Zach Collins,1628380,1,1,1,5,6,8,5,4,7,11,...,17,1,10,1,3,1,1,5,2,2
Zach LaVine,203897,1,1,1,10,4,10,13,7,18,22,...,29,1,11,1,5,1,1,10,2,2
Zach Lofton,1629155,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Zaza Pachulia,2585,1,1,1,5,3,8,2,1,1,8,...,11,1,12,1,3,1,1,4,2,2
Zhaire Smith,1629015,1,1,1,4,2,4,5,3,6,5,...,5,1,5,1,2,1,1,3,1,2
Zhou Qi,1627753,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [122]:
#your code here
len(df.groupby(["DISPLAY_FIRST_LAST", "PERSON_ID"]).nunique()[(df.groupby(["DISPLAY_FIRST_LAST", "PERSON_ID"]).nunique()["TEAM_ID_y"] > 1)])

86

In [125]:
df.groupby(["DISPLAY_FIRST_LAST", "PERSON_ID"]).nunique()[(df.groupby(["DISPLAY_FIRST_LAST", "PERSON_ID"]).nunique()["TEAM_ID_y"] > 1)]["TEAM_ID_y"].max()

3

## 7:

Find the player who scored the least amount of points while playing in at least 40 games last season.

In [154]:
#your code here
players = df.groupby("DISPLAY_FIRST_LAST").agg({"DISPLAY_FIRST_LAS": "count", "PTS": "sum"})
players[players["DISPLAY_FIRST_LAST"] >= 40]["PTS"].idxmin()

'Sindarius Thornwell'

# Part 4: Pandas and Probability

## 8: 

What is the probability that a random player had a game where they scored more than 40 points?

In [162]:
#your code here
len(df[df["PTS"] > 40])/len(df)

0.004214397915788667

## 9:

What is the probability that a randomly selected player from last season would average more than 20 points per game?

In [177]:
# your code here
players = df.groupby("DISPLAY_FIRST_LAST").agg({"PTS": 'mean'})["PTS"] > 20
players.sum()/len(df["DISPLAY_FIRST_LAST"].unique())

0.062264150943396226

# Advanced Questions

## 10: 
Find the player who scored the least amount of points while playing in at least 40 games and averageing at least 15 minutes per game last season.

In [192]:
#your code here
grouped = df.groupby("DISPLAY_FIRST_LAST").agg({"PTS": "sum", "DISPLAY_FIRST_LAST": "count", "MIN": 'mean'})
grouped[(df.groupby("DISPLAY_FIRST_LAST").agg({"MIN": 'mean'})["MIN"] >= 15) & (df.groupby("DISPLAY_FIRST_LAST").agg({"DISPLAY_FIRST_LAST": "count"})["DISPLAY_FIRST_LAST"] >= 40)].sort_values("PTS").head(1)

                    PTS  DISPLAY_FIRST_LAST        MIN
DISPLAY_FIRST_LAST
Tyson Chandler      173                  55  15.927273

## 11: 
Which player scored the largest share of points for their team throughout the season.

In [222]:
#your code here

## 12:

What is the probability that a randomly selected player had at least one game in which they scored 40 points last season.

In [182]:
# your code here
len(df[df["PTS"] >= 40]["DISPLAY_FIRST_LAST"].unique())/len(df["DISPLAY_FIRST_LAST"].unique())

0.06981132075471698

## 13: 

A double-double is when a player records 10 or more stats for any of the two follow categories: points, rebounds, assists, steals, or blocks. 
What is the probability that a randomly selected player had a double-double in a game last season?

In [ ]:
#your code here

## 14:

What is the probability that a randomnly selected game had a player record a triple-double in that game?

In [ ]:
#your code here

# Part 5: Super Duper Challenge

## 15:

How many players last season averaged more points per game than their career average?